name: bioscan-curation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake
  - mamba
  - sqlite
  - perl-bio-phylo-forest-dbtree
  - perl-text-csv_xs
  - perl-log-log4perl
  - perl-module-load
  - perl-json
  - hmmer
