name: bold-curation
channels:
  - conda-forge
  - bioconda
  - eumetsat
  - defaults
dependencies:
  - snakemake
  - mamba
  - sqlite
  - perl-bio-phylo-forest-dbtree
  - perl-text-csv_xs
  - perl-log-log4perl
  - perl-module-load
  - perl-json
  - perl-libwww-perl
  - perl-lwp-protocol-https
  - perl-dbd-sqlite
  - hmmer
