name: bold-curation
channels:
  - conda-forge
  - bioconda
  - eumetsat
  - defaults
dependencies:
  - snakemake = 8.10.7
  - mamba = 1.5.8
  - sqlite = 3.45.3
  - perl-bio-phylo-forest-dbtree
  - perl-text-csv_xs
  - perl-log-log4perl
  - perl-module-load
  - perl-json
  - perl-libwww-perl
  - perl-lwp-protocol-https
  - perl-dbd-sqlite
  - hmmer
  - jq
  - curl

