config:
BOLD_TSV: resources/BOLD_Public.05-Apr-2024.tsv
DB_FILE: results/bold.db
SCHEMA: workflow/scripts/schema.sql
INDEXES: workflow/scripts/indexes.sql
LIBS: lib/
PATH: lib/
TAXONOMY_LOADED: results/taxonomy_check.tsv
CRITERIA: "COLLECTION_DATE COLLECTORS COORD COUNTRY HAS_IMAGE IDENTIFIER ID_METHOD INSTITUTION MUSEUM_ID PUBLIC_VOUCHER SEQ_QUALITY SITE SPECIES_ID TYPE_SPECIMEN"
DB_FILE_INDEXED: results/bold_indexed.ok
TARGET_LIST: resources/all_specs_and_syn.csv
PROJECT_NAME: "bold-curation"
TAXON_LEVEL: "species"
KINGDOM: "Animalia"
LOG_LEVEL: "INFO" 
DB_CRITERIA_ADDED: results/criteria_indexed
